[0m16:18:46.779087 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12d4b5ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12d4b53d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12d517fd0>]}


============================== 16:18:46.780739 | 6378dc01-242e-4a6a-8ab9-ae2c7339bf00 ==============================
[0m16:18:46.780739 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:18:46.781033 [debug] [MainThread]: running dbt with arguments {'cache_selected_only': 'False', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'log_format': 'default', 'fail_fast': 'False', 'profiles_dir': '/Users/yoki/.dbt', 'use_experimental_parser': 'False', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'indirect_selection': 'eager', 'introspect': 'True', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'debug': 'False', 'quiet': 'False', 'write_json': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'version_check': 'True', 'printer_width': '80', 'log_cache_events': 'False', 'use_colors': 'True', 'warn_error': 'None', 'partial_parse': 'True', 'empty': 'False'}
[0m16:18:47.598288 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12d4dde10>]}
[0m16:18:47.615673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11f5ecf10>]}
[0m16:18:47.616009 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m16:18:47.626563 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m16:18:47.627149 [info ] [MainThread]: Unable to do partial parsing because saved manifest not found. Starting full parse.
[0m16:18:47.627370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x173b37c90>]}
[0m16:18:48.077972 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x173e97150>]}
[0m16:18:48.115952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1738b2550>]}
[0m16:18:48.116205 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m16:18:48.116358 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '6378dc01-242e-4a6a-8ab9-ae2c7339bf00', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x173dc7350>]}
[0m16:18:48.116945 [info ] [MainThread]: 
[0m16:18:48.117404 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m16:18:48.118877 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m16:18:48.119083 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:18:48.119754 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: '[Errno 2] No such file or directory: './dbt-cred.json''
[0m16:18:48.120023 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:18:48.120152 [debug] [MainThread]: Connection 'list_inlaid-reactor-427616-m8' was properly closed.
[0m16:18:48.120271 [info ] [MainThread]: 
[0m16:18:48.120400 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.00 seconds (0.00s).
[0m16:18:48.120596 [error] [MainThread]: Encountered an error:
Database Error
  [Errno 2] No such file or directory: './dbt-cred.json'
[0m16:18:48.120797 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 1.3661997, "process_user_time": 4.093725, "process_kernel_time": 0.347795, "process_mem_max_rss": "236453888", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:18:48.121008 [debug] [MainThread]: Command `dbt run` failed at 16:18:48.120972 after 1.37 seconds
[0m16:18:48.121156 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105148e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12d4f4210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x173ded4d0>]}
[0m16:18:48.121296 [debug] [MainThread]: Flushing usage events
[0m16:18:55.940327 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1685b5990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16860ffd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x157f99590>]}


============================== 16:18:55.942100 | b23b0595-7ed2-4fb9-a0ff-1dbd64613409 ==============================
[0m16:18:55.942100 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:18:55.942447 [debug] [MainThread]: running dbt with arguments {'no_print': 'None', 'log_format': 'default', 'write_json': 'True', 'indirect_selection': 'eager', 'target_path': 'None', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'warn_error': 'None', 'fail_fast': 'False', 'empty': 'False', 'partial_parse': 'True', 'log_cache_events': 'False', 'use_colors': 'True', 'static_parser': 'True', 'printer_width': '80', 'version_check': 'True', 'cache_selected_only': 'False', 'use_experimental_parser': 'False', 'profiles_dir': '/Users/yoki/.dbt', 'debug': 'False', 'introspect': 'True', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])'}
[0m16:18:56.550396 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'b23b0595-7ed2-4fb9-a0ff-1dbd64613409', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1577dbcd0>]}
[0m16:18:56.568460 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'b23b0595-7ed2-4fb9-a0ff-1dbd64613409', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1566f0d50>]}
[0m16:18:56.568892 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m16:18:56.577800 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m16:18:56.634867 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m16:18:56.635140 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m16:18:56.647857 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'b23b0595-7ed2-4fb9-a0ff-1dbd64613409', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x303bdc210>]}
[0m16:18:56.686570 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'b23b0595-7ed2-4fb9-a0ff-1dbd64613409', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x303dbf250>]}
[0m16:18:56.686897 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m16:18:56.687059 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'b23b0595-7ed2-4fb9-a0ff-1dbd64613409', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x30331d390>]}
[0m16:18:56.687790 [info ] [MainThread]: 
[0m16:18:56.688087 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m16:18:56.689649 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m16:18:56.689871 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m16:18:57.821521 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_inlaid-reactor-427616-m8, now create_inlaid-reactor-427616-m8_mage-de-demo)
[0m16:18:57.824251 [debug] [ThreadPool]: Creating schema "database: "inlaid-reactor-427616-m8"
schema: "mage-de-demo"
"
[0m16:18:57.838515 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m16:18:57.883640 [debug] [ThreadPool]: On create_inlaid-reactor-427616-m8_mage-de-demo: /* {"app": "dbt", "dbt_version": "1.8.3", "profile_name": "dbt_demo", "target_name": "dev", "connection_name": "create_inlaid-reactor-427616-m8_mage-de-demo"} */
create schema if not exists `inlaid-reactor-427616-m8`.`mage-de-demo`
  
[0m16:18:58.427222 [error] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=inlaid-reactor-427616-m8&j=bq:US:da98909d-2abb-4fce-a0bc-81e24e8bf0f0&page=queryresults
[0m16:18:58.428333 [debug] [ThreadPool]: BigQuery adapter: Unhandled error while running:
macro create_schema
[0m16:18:58.428823 [debug] [ThreadPool]: BigQuery adapter: Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m16:18:58.429620 [debug] [MainThread]: Connection 'master' was properly closed.
[0m16:18:58.429910 [debug] [MainThread]: Connection 'create_inlaid-reactor-427616-m8_mage-de-demo' was properly closed.
[0m16:18:58.430223 [info ] [MainThread]: 
[0m16:18:58.430637 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.74 seconds (1.74s).
[0m16:18:58.431168 [error] [MainThread]: Encountered an error:
Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m16:18:58.431746 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 2.517442, "process_user_time": 2.764338, "process_kernel_time": 1.125718, "process_mem_max_rss": "241500160", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m16:18:58.432372 [debug] [MainThread]: Command `dbt run` failed at 16:18:58.432271 after 2.52 seconds
[0m16:18:58.432793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105000e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16861b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1685b6190>]}
[0m16:18:58.433197 [debug] [MainThread]: Flushing usage events
[0m11:06:33.404429 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131df1b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131e43990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131e43fd0>]}


============================== 11:06:33.407239 | 91b3261f-752b-415e-a14a-0570ec01fa12 ==============================
[0m11:06:33.407239 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:06:33.407550 [debug] [MainThread]: running dbt with arguments {'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'indirect_selection': 'eager', 'use_experimental_parser': 'False', 'quiet': 'False', 'invocation_command': 'dbt run', 'warn_error': 'None', 'printer_width': '80', 'send_anonymous_usage_stats': 'True', 'debug': 'False', 'version_check': 'True', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'target_path': 'None', 'no_print': 'None', 'log_cache_events': 'False', 'static_parser': 'True', 'log_format': 'default', 'empty': 'False', 'fail_fast': 'False', 'introspect': 'True', 'write_json': 'True', 'profiles_dir': '/Users/yoki/.dbt', 'cache_selected_only': 'False', 'use_colors': 'True', 'partial_parse': 'True'}
[0m11:06:34.584975 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '91b3261f-752b-415e-a14a-0570ec01fa12', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1555407d0>]}
[0m11:06:34.601839 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '91b3261f-752b-415e-a14a-0570ec01fa12', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x130164f50>]}
[0m11:06:34.602090 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m11:06:34.612018 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m11:06:34.667223 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m11:06:34.667446 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m11:06:34.680197 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '91b3261f-752b-415e-a14a-0570ec01fa12', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131772fd0>]}
[0m11:06:34.722684 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '91b3261f-752b-415e-a14a-0570ec01fa12', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1562bebd0>]}
[0m11:06:34.722988 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m11:06:34.723159 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '91b3261f-752b-415e-a14a-0570ec01fa12', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1557c1f10>]}
[0m11:06:34.723767 [info ] [MainThread]: 
[0m11:06:34.724057 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:06:34.725532 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m11:06:34.725731 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:06:35.403831 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_inlaid-reactor-427616-m8, now create_inlaid-reactor-427616-m8_mage-de-demo)
[0m11:06:35.405488 [debug] [ThreadPool]: Creating schema "database: "inlaid-reactor-427616-m8"
schema: "mage-de-demo"
"
[0m11:06:35.420396 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m11:06:35.466052 [debug] [ThreadPool]: On create_inlaid-reactor-427616-m8_mage-de-demo: /* {"app": "dbt", "dbt_version": "1.8.3", "profile_name": "dbt_demo", "target_name": "dev", "connection_name": "create_inlaid-reactor-427616-m8_mage-de-demo"} */
create schema if not exists `inlaid-reactor-427616-m8`.`mage-de-demo`
  
[0m11:06:35.908282 [error] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=inlaid-reactor-427616-m8&j=bq:US:6947ea5c-ec86-4bae-b7d1-446b10261b3f&page=queryresults
[0m11:06:35.909343 [debug] [ThreadPool]: BigQuery adapter: Unhandled error while running:
macro create_schema
[0m11:06:35.909846 [debug] [ThreadPool]: BigQuery adapter: Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:06:35.910744 [debug] [MainThread]: Connection 'master' was properly closed.
[0m11:06:35.911106 [debug] [MainThread]: Connection 'create_inlaid-reactor-427616-m8_mage-de-demo' was properly closed.
[0m11:06:35.911439 [info ] [MainThread]: 
[0m11:06:35.911788 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.19 seconds (1.19s).
[0m11:06:35.912277 [error] [MainThread]: Encountered an error:
Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:06:35.912860 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 2.5392752, "process_user_time": 1.90518, "process_kernel_time": 2.445974, "process_mem_max_rss": "242384896", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:06:35.913595 [debug] [MainThread]: Command `dbt run` failed at 11:06:35.913324 after 2.54 seconds
[0m11:06:35.914414 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x131e438d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100c9ce50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1562fb8d0>]}
[0m11:06:35.914934 [debug] [MainThread]: Flushing usage events
[0m11:12:07.006572 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1601f2f90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16040fcd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16040ff90>]}


============================== 11:12:07.009295 | d57311e4-58d0-4f65-8acc-60cbd0ac16b6 ==============================
[0m11:12:07.009295 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:12:07.009706 [debug] [MainThread]: running dbt with arguments {'no_print': 'None', 'empty': 'False', 'fail_fast': 'False', 'static_parser': 'True', 'write_json': 'True', 'quiet': 'False', 'log_cache_events': 'False', 'warn_error': 'None', 'introspect': 'True', 'profiles_dir': '/Users/yoki/.dbt', 'debug': 'False', 'send_anonymous_usage_stats': 'True', 'partial_parse': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'version_check': 'True', 'use_colors': 'True', 'target_path': 'None', 'cache_selected_only': 'False', 'indirect_selection': 'eager', 'printer_width': '80', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'log_format': 'default', 'use_experimental_parser': 'False', 'invocation_command': 'dbt run'}
[0m11:12:07.966575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16041e610>]}
[0m11:12:07.984157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x14e55d550>]}
[0m11:12:07.984476 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m11:12:07.995661 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m11:12:08.038569 [info ] [MainThread]: Unable to do partial parsing because a project config has changed
[0m11:12:08.038893 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x14ed60dd0>]}
[0m11:12:08.489914 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.tip_model.staging
- models.tip_model.core
[0m11:12:08.491994 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16cb3bed0>]}
[0m11:12:08.531354 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16c976850>]}
[0m11:12:08.531682 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m11:12:08.531847 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'd57311e4-58d0-4f65-8acc-60cbd0ac16b6', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16c936e90>]}
[0m11:12:08.532451 [info ] [MainThread]: 
[0m11:12:08.532687 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:12:08.534214 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m11:12:08.534405 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:12:09.304637 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_inlaid-reactor-427616-m8, now create_inlaid-reactor-427616-m8_mage-de-demo)
[0m11:12:09.305862 [debug] [ThreadPool]: Creating schema "database: "inlaid-reactor-427616-m8"
schema: "mage-de-demo"
"
[0m11:12:09.316907 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m11:12:09.356011 [debug] [ThreadPool]: On create_inlaid-reactor-427616-m8_mage-de-demo: /* {"app": "dbt", "dbt_version": "1.8.3", "profile_name": "dbt_demo", "target_name": "dev", "connection_name": "create_inlaid-reactor-427616-m8_mage-de-demo"} */
create schema if not exists `inlaid-reactor-427616-m8`.`mage-de-demo`
  
[0m11:12:09.829018 [error] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=inlaid-reactor-427616-m8&j=bq:US:d0478885-b7a7-4298-aced-b979fa9c6481&page=queryresults
[0m11:12:09.830452 [debug] [ThreadPool]: BigQuery adapter: Unhandled error while running:
macro create_schema
[0m11:12:09.831133 [debug] [ThreadPool]: BigQuery adapter: Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:12:09.833151 [debug] [MainThread]: Connection 'master' was properly closed.
[0m11:12:09.833721 [debug] [MainThread]: Connection 'create_inlaid-reactor-427616-m8_mage-de-demo' was properly closed.
[0m11:12:09.834227 [info ] [MainThread]: 
[0m11:12:09.834767 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 1.30 seconds (1.30s).
[0m11:12:09.835494 [error] [MainThread]: Encountered an error:
Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:12:09.836378 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 2.8605766, "process_user_time": 2.12779, "process_kernel_time": 2.507585, "process_mem_max_rss": "245448704", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:12:09.837289 [debug] [MainThread]: Command `dbt run` failed at 11:12:09.837176 after 2.86 seconds
[0m11:12:09.837864 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16020bb50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1602085d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d24d90>]}
[0m11:12:09.838408 [debug] [MainThread]: Flushing usage events
[0m11:14:41.705403 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1561b56d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x156217b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x156217f90>]}


============================== 11:14:41.708210 | 1348dcd3-0e54-452c-a8fa-6535626824d0 ==============================
[0m11:14:41.708210 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:14:41.708567 [debug] [MainThread]: running dbt with arguments {'write_json': 'True', 'fail_fast': 'False', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'send_anonymous_usage_stats': 'True', 'target_path': 'None', 'log_format': 'default', 'printer_width': '80', 'debug': 'False', 'profiles_dir': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo', 'partial_parse': 'True', 'use_colors': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'warn_error': 'None', 'no_print': 'None', 'cache_selected_only': 'False', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'quiet': 'False', 'use_experimental_parser': 'False', 'version_check': 'True', 'static_parser': 'True', 'empty': 'False', 'introspect': 'True'}
[0m11:14:41.709918 [error] [MainThread]: Encountered an error:
Runtime Error
  Could not find profile named 'dbt_demo'
[0m11:14:41.711393 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.0338025, "process_user_time": 0.899093, "process_kernel_time": 2.408695, "process_mem_max_rss": "116244480", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:14:41.711723 [debug] [MainThread]: Command `dbt run` failed at 11:14:41.711679 after 0.03 seconds
[0m11:14:41.711906 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x15621bf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102c9ce50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1562176d0>]}
[0m11:14:41.712062 [debug] [MainThread]: Flushing usage events
[0m11:19:42.904765 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e8b5790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e376b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e91d210>]}


============================== 11:19:42.907049 | 7e2fc0e9-97a2-4c95-8e7b-411725b95399 ==============================
[0m11:19:42.907049 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:19:42.907402 [debug] [MainThread]: running dbt with arguments {'version_check': 'True', 'quiet': 'False', 'log_format': 'default', 'write_json': 'True', 'target_path': 'None', 'debug': 'False', 'warn_error': 'None', 'partial_parse': 'True', 'static_parser': 'True', 'no_print': 'None', 'profiles_dir': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo', 'use_experimental_parser': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'fail_fast': 'False', 'log_cache_events': 'False', 'invocation_command': 'dbt run', 'empty': 'False', 'send_anonymous_usage_stats': 'True', 'indirect_selection': 'eager', 'printer_width': '80', 'cache_selected_only': 'False', 'introspect': 'True', 'use_colors': 'True', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs'}
[0m11:19:43.849086 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1728fee50>]}
[0m11:19:43.866542 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13c968c10>]}
[0m11:19:43.866815 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m11:19:43.877206 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m11:19:43.919020 [info ] [MainThread]: Unable to do partial parsing because profile has changed
[0m11:19:43.919292 [info ] [MainThread]: Unable to do partial parsing because a project dependency has been added
[0m11:19:43.919461 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'partial_parser', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13d258fd0>]}
[0m11:19:44.364916 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.tip_model.staging
- models.tip_model.core
[0m11:19:44.366917 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1729cd510>]}
[0m11:19:44.404158 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x174549110>]}
[0m11:19:44.404438 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m11:19:44.404605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '7e2fc0e9-97a2-4c95-8e7b-411725b95399', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x172d997d0>]}
[0m11:19:44.405196 [info ] [MainThread]: 
[0m11:19:44.405445 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:19:44.406924 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m11:19:44.407106 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:19:50.414989 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:19:50.417490 [debug] [MainThread]: Connection 'master' was properly closed.
[0m11:19:50.418030 [debug] [MainThread]: Connection 'list_inlaid-reactor-427616-m8' was properly closed.
[0m11:19:50.418518 [info ] [MainThread]: 
[0m11:19:50.419101 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 6.01 seconds (6.01s).
[0m11:19:50.419908 [error] [MainThread]: Encountered an error:
Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m11:19:50.420601 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 7.5404105, "process_user_time": 1.858128, "process_kernel_time": 2.542966, "process_mem_max_rss": "236830720", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:19:50.421271 [debug] [MainThread]: Command `dbt run` failed at 11:19:50.421174 after 7.54 seconds
[0m11:19:50.421767 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103150e50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e91cc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x13e91cad0>]}
[0m11:19:50.422303 [debug] [MainThread]: Flushing usage events
[0m11:22:21.105250 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1685f1950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16864bed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x16864bfd0>]}


============================== 11:22:21.108058 | f18c8d20-0433-4281-83c4-feeeb26f785d ==============================
[0m11:22:21.108058 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:22:21.108442 [debug] [MainThread]: running dbt with arguments {'target_path': 'None', 'warn_error': 'None', 'partial_parse': 'True', 'send_anonymous_usage_stats': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'indirect_selection': 'eager', 'write_json': 'True', 'cache_selected_only': 'False', 'fail_fast': 'False', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'no_print': 'None', 'printer_width': '80', 'use_experimental_parser': 'False', 'log_format': 'default', 'debug': 'False', 'use_colors': 'True', 'version_check': 'True', 'quiet': 'False', 'empty': 'False', 'static_parser': 'True', 'log_cache_events': 'False', 'introspect': 'True', 'profiles_dir': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo'}
[0m11:22:22.045790 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': 'f18c8d20-0433-4281-83c4-feeeb26f785d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x30441b3d0>]}
[0m11:22:22.062870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': 'f18c8d20-0433-4281-83c4-feeeb26f785d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x12f568d90>]}
[0m11:22:22.063139 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m11:22:22.073132 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m11:22:22.130606 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m11:22:22.130825 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m11:22:22.132718 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.tip_model.staging
- models.tip_model.core
[0m11:22:22.143882 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': 'f18c8d20-0433-4281-83c4-feeeb26f785d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x304518790>]}
[0m11:22:22.183480 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': 'f18c8d20-0433-4281-83c4-feeeb26f785d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x3047bf090>]}
[0m11:22:22.183756 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m11:22:22.183913 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': 'f18c8d20-0433-4281-83c4-feeeb26f785d', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x304694e90>]}
[0m11:22:22.184576 [info ] [MainThread]: 
[0m11:22:22.184867 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:22:22.186439 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m11:22:22.186673 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:22:28.195624 [debug] [ThreadPool]: BigQuery adapter: Got an error when attempting to create a bigquery client: 'Runtime Error
  Failed to authenticate with supplied credentials
  error:
  Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.'
[0m11:22:28.197735 [debug] [MainThread]: Connection 'master' was properly closed.
[0m11:22:28.198349 [debug] [MainThread]: Connection 'list_inlaid-reactor-427616-m8' was properly closed.
[0m11:22:28.198953 [info ] [MainThread]: 
[0m11:22:28.199572 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 6.01 seconds (6.01s).
[0m11:22:28.203225 [error] [MainThread]: Encountered an error:
Database Error
  Runtime Error
    Failed to authenticate with supplied credentials
    error:
    Your default credentials were not found. To set up Application Default Credentials, see https://cloud.google.com/docs/authentication/external/set-up-adc for more information.
[0m11:22:28.204228 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 7.125726, "process_user_time": 1.584531, "process_kernel_time": 2.418465, "process_mem_max_rss": "233865216", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:22:28.205187 [debug] [MainThread]: Command `dbt run` failed at 11:22:28.205061 after 7.13 seconds
[0m11:22:28.205891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1052b8e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168631a90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1686308d0>]}
[0m11:22:28.206484 [debug] [MainThread]: Flushing usage events
[0m11:25:46.700071 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168bf2010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168c43fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168c43f90>]}


============================== 11:25:46.702237 | 19351d02-14d6-4986-956d-938e914648a9 ==============================
[0m11:25:46.702237 [info ] [MainThread]: Running with dbt=1.8.3
[0m11:25:46.702592 [debug] [MainThread]: running dbt with arguments {'invocation_command': 'dbt run', 'target_path': 'None', 'log_cache_events': 'False', 'version_check': 'True', 'introspect': 'True', 'send_anonymous_usage_stats': 'True', 'no_print': 'None', 'printer_width': '80', 'debug': 'False', 'warn_error': 'None', 'static_parser': 'True', 'use_experimental_parser': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'profiles_dir': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo', 'log_path': '/Users/yoki/Desktop/DE/4_dbt/dbt_demo/logs', 'cache_selected_only': 'False', 'empty': 'False', 'indirect_selection': 'eager', 'use_colors': 'True', 'quiet': 'False', 'log_format': 'default', 'fail_fast': 'False', 'write_json': 'True', 'partial_parse': 'True'}
[0m11:25:47.560370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'project_id', 'label': '19351d02-14d6-4986-956d-938e914648a9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x168bf36d0>]}
[0m11:25:47.578222 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'adapter_info', 'label': '19351d02-14d6-4986-956d-938e914648a9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x146f68c10>]}
[0m11:25:47.578598 [info ] [MainThread]: Registered adapter: bigquery=1.8.2
[0m11:25:47.588880 [debug] [MainThread]: checksum: 30bd4080c2bc8dee5936f8f60083ffbe1c906859d0fd965607c2144031479456, vars: {}, profile: , target: , version: 1.8.3
[0m11:25:47.646063 [debug] [MainThread]: Partial parsing enabled: 0 files deleted, 0 files added, 0 files changed.
[0m11:25:47.646307 [debug] [MainThread]: Partial parsing enabled, no changes found, skipping parsing
[0m11:25:47.648261 [warn ] [MainThread]: [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 2 unused configuration paths:
- models.tip_model.staging
- models.tip_model.core
[0m11:25:47.659923 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'load_project', 'label': '19351d02-14d6-4986-956d-938e914648a9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x17c0de110>]}
[0m11:25:47.697535 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'resource_counts', 'label': '19351d02-14d6-4986-956d-938e914648a9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x17c3bfc50>]}
[0m11:25:47.697809 [info ] [MainThread]: Found 2 models, 4 data tests, 471 macros
[0m11:25:47.697974 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'runnable_timing', 'label': '19351d02-14d6-4986-956d-938e914648a9', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x17c07e550>]}
[0m11:25:47.698614 [info ] [MainThread]: 
[0m11:25:47.698903 [debug] [MainThread]: Acquiring new bigquery connection 'master'
[0m11:25:47.700374 [debug] [ThreadPool]: Acquiring new bigquery connection 'list_inlaid-reactor-427616-m8'
[0m11:25:47.700556 [debug] [ThreadPool]: Opening a new connection, currently in state init
[0m11:25:48.325566 [debug] [ThreadPool]: Re-using an available connection from the pool (formerly list_inlaid-reactor-427616-m8, now create_inlaid-reactor-427616-m8_mage-de-demo)
[0m11:25:48.327703 [debug] [ThreadPool]: Creating schema "database: "inlaid-reactor-427616-m8"
schema: "mage-de-demo"
"
[0m11:25:48.343462 [debug] [ThreadPool]: Opening a new connection, currently in state closed
[0m11:25:48.344361 [debug] [ThreadPool]: On create_inlaid-reactor-427616-m8_mage-de-demo: /* {"app": "dbt", "dbt_version": "1.8.3", "profile_name": "terra_demo", "target_name": "dev", "connection_name": "create_inlaid-reactor-427616-m8_mage-de-demo"} */
create schema if not exists `inlaid-reactor-427616-m8`.`mage-de-demo`
  
[0m11:25:48.618426 [error] [ThreadPool]: BigQuery adapter: https://console.cloud.google.com/bigquery?project=inlaid-reactor-427616-m8&j=bq:US:f6682f91-461f-434c-b19e-73bcea243389&page=queryresults
[0m11:25:48.626486 [debug] [ThreadPool]: BigQuery adapter: Unhandled error while running:
macro create_schema
[0m11:25:48.627178 [debug] [ThreadPool]: BigQuery adapter: Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:25:48.628037 [debug] [MainThread]: Connection 'master' was properly closed.
[0m11:25:48.628331 [debug] [MainThread]: Connection 'create_inlaid-reactor-427616-m8_mage-de-demo' was properly closed.
[0m11:25:48.628641 [info ] [MainThread]: 
[0m11:25:48.628997 [info ] [MainThread]: Finished running  in 0 hours 0 minutes and 0.93 seconds (0.93s).
[0m11:25:48.629467 [error] [MainThread]: Encountered an error:
Database Error
  Access Denied: Project inlaid-reactor-427616-m8: User does not have bigquery.jobs.create permission in project inlaid-reactor-427616-m8.
[0m11:25:48.629981 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 1.9562722, "process_user_time": 1.634008, "process_kernel_time": 2.453334, "process_mem_max_rss": "240123904", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:25:48.630546 [debug] [MainThread]: Command `dbt run` failed at 11:25:48.630452 after 1.96 seconds
[0m11:25:48.630901 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1686f3990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1056f0f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x17e00c2d0>]}
[0m11:25:48.631269 [debug] [MainThread]: Flushing usage events
